FROM --platform=linux/amd64 mirror.gcr.io/library/python:3.12-slim@sha256:78387bc3881b8273120a12ebe6c1ab22b018ccc2c9adf565ae1ac9b536e184ea
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py start.sh ./
RUN chmod 0555 /app/start.sh
ENTRYPOINT ["/app/start.sh"]
